[features]
seeds = false
skip-lint = false
[programs.localnet]
solang = "5jkbKtTNFF5crf3ASmVkAuZQGT7WAuLdumrzUCH3MscG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
